apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}
  {{- with .Values.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  admin-user: {{ .Values.adminUser }}
  admin-password: {{ .Values.adminPassword }}
