
replicaCount: 1

labels:
  k8s-app: grafana
  app.kubernetes.io/name: grafana
  app.kubernetes.io/component: grafana

commonAnnotations:
  annotations:
    prometheus.io/scrape: 'true'

image:
  repository: grafana/grafana
  pullPolicy: IfNotPresent
  tag: 7.5.7

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""


volumeMounts:
  - name: config
    mountPath: "/etc/grafana/"
  - name: dashboards
    mountPath: "/var/lib/grafana/dashboards"
  - name: datasources
    mountPath: "/etc/grafana/provisioning/datasources/"
  - name: dashboardproviders
    mountPath: "/etc/grafana/provisioning/dashboards/"

volumes:
  - name: config
    configMap:
      name: grafana-ini
  - name: datasources
    configMap:
      name: grafana-datasources
  - name: dashboardproviders
    configMap:
      name: grafana-dashboardproviders
  - name: dashboards
    configMap:
      name: dashboards

probs:
  readinessProbe:
    enabled: true
    readinessProbe:
      httpGet:
        path: /api/health
        port: 3000
  livenessProbe:
    enabled: true
    livenessProbe:
      httpGet:
        path: /api/health
        port: 3000
      initialDelaySeconds: 30
      timeoutSeconds: 30
      failureThreshold: 10
      periodSeconds: 10

podAnnotations: {}

adminUser: YWRtaW4=
adminPassword: YWRtaW4=

podSecurityContext: {}
securityContext: {}
service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []
  tls: []

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

templates:
  dashboard.json: |-
    {
      "annotations": {
        "list": [
          {
            "builtIn": 1,
            "datasource": "-- Grafana --",
            "enable": true,
            "hide": true,
            "iconColor": "rgba(0, 211, 255, 1)",
            "name": "Annotations & Alerts",
            "type": "dashboard"
          }
        ]
      },
      "editable": true,
      "gnetId": null,
      "graphTooltip": 0,
      "id": 2,
      "iteration": 1623756658782,
      "links": [],
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false,
          "datasource": null,
          "fieldConfig": {
            "defaults": {},
            "overrides": []
          },
          "fill": 1,
          "fillGradient": 0,
          "gridPos": {
            "h": 9,
            "w": 12,
            "x": 0,
            "y": 0
          },
          "hiddenSeries": false,
          "id": 2,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "nullPointMode": "null",
          "options": {
            "alertThreshold": true
          },
          "percentage": false,
          "pluginVersion": "7.5.7",
          "pointradius": 2,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "spaceLength": 10,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "exemplar": true,
              "expr": "system_process_count {HostIP=\"$HostIP\"}",
              "interval": "",
              "legendFormat": "{{ HostIP }}",
              "refId": "A"
            }
          ],
          "thresholds": [],
          "timeFrom": null,
          "timeRegions": [],
          "timeShift": null,
          "title": "Total process count per node",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
          "xaxis": {
            "buckets": null,
            "mode": "time",
            "name": null,
            "show": true,
            "values": []
          },
          "yaxes": [
            {
              "$$hashKey": "object:149",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "$$hashKey": "object:150",
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "yaxis": {
            "align": false,
            "alignLevel": null
          }
        }
      ],
      "refresh": false,
      "schemaVersion": 27,
      "style": "dark",
      "tags": [],
      "templating": {
        "list": [
          {
            "allValue": null,
            "current": {
              "selected": true,
              "text": "10.1.18.106",
              "value": "10.1.18.106"
            },
            "datasource": null,
            "definition": "label_values(system_process_count{job=\"kubernetes-service-endpoints\"}, HostIP)",
            "description": null,
            "error": null,
            "hide": 0,
            "includeAll": false,
            "label": null,
            "multi": false,
            "name": "HostIP",
            "options": [],
            "query": {
              "query": "label_values(system_process_count{job=\"kubernetes-service-endpoints\"}, HostIP)",
              "refId": "StandardVariableQuery"
            },
            "refresh": 1,
            "regex": "",
            "skipUrlSync": false,
            "sort": 0,
            "tagValuesQuery": "",
            "tags": [],
            "tagsQuery": "",
            "type": "query",
            "useTags": false
          }
        ]
      },
      "time": {
        "from": "now-5m",
        "to": "now"
      },
      "timepicker": {},
      "timezone": "",
      "title": "Dashboard-TechAssignment",
      "uid": "opdVOOR7z",
      "version": 7
    }
