replicaCount: 5

labels:
  k8s-app: process-counter-exporter

commonAnnotations:
  annotations:
    prometheus.io/scrape: 'true'

image:
  repository: thataucsc/custom-exporter
  pullPolicy: IfNotPresent
  tag: v1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}


service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false
  annotations: {}

  hosts:
    - host: chart-example.local
      paths: []
  tls: []


resources:

  limits:
    cpu: 10m
    memory: 50Mi
  requests:
    cpu: 10m
    memory: 50Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
