apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alertmanager.serviceAccountName" . }}-config
  {{- with .Values.labels}}
  labels:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.commonAnnotations.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- with .Values.templates }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
